name: "base:ffmpeg-cuda-ubuntu"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "**"

jobs:
  docker:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cardinalby/export-env-action@v1
        with:
          envFile: "Build.ubuntu.env"
          export: "true"
          expandWithJobEnv: "true"
          expand: "true"

      - uses: cardinalby/export-env-action@v1
        with:
          envFile: "Build.ubuntu.cuda.env"
          export: "true"
          expandWithJobEnv: "true"
          expand: "true"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Multi-Arch
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile.ubuntu.cuda
          build-args: |
            BUILD_IMAGE=nvidia/cuda:${{ env.CUDA_VERSION }}-devel-${{ env.OS_NAME }}${{ env.OS_VERSION }}
            DEPLOY_IMAGE=nvidia/cuda:${{ env.CUDA_VERSION }}-runtime-${{ env.OS_NAME }}${{ env.OS_VERSION }}
            FFNVCODEC_VERSION=${{ env.FFNVCODEC_VERSION }}
            FREETYPE_VERSION=${{ env.FREETYPE_VERSION }}
            XML2_VERSION=${{ env.XML2_VERSION }}
            SRT_VERSION=${{ env.SRT_VERSION }}
            X264_VERSION=${{ env.X264_VERSION }}
            X265_VERSION=${{ env.X265_VERSION }}
            VPX_VERSION=${{ env.VPX_VERSION }}
            LAME_VERSION=${{ env.LAME_VERSION }}
            OPUS_VERSION=${{ env.OPUS_VERSION }}
            OGG_VERSION=${{ env.OGG_VERSION }}
            VORBIS_VERSION=${{ env.VORBIS_VERSION }}
            DAV1D_VERSION=${{ env.DAV1D_VERSION }}
            RAV1E_VERSION=${{ env.RAV1E_VERSION }}
            FFMPEG_VERSION=${{ env.FFMPEG_VERSION }}
          platforms: linux/amd64
          push: true
          tags: |
            datarhei/base:${{ env.OS_NAME }}-ffmpeg-cuda-${{ env.OS_VERSION }}-${{ env.FFMPEG_VERSION }}-${{env.CUDA_VERSION}}
            datarhei/base:ffmpeg${{ env.FFMPEG_VERSION }}-cuda-${{ env.OS_NAME }}${{ env.OS_VERSION }}-cuda${{env.CUDA_VERSION}}
